matrix:
  include:
    - os: linux
      dist: trusty
      env:
        - CXX="$HOME/llvm/bin/clang++"
        - CPPFLAGS="-I $HOME/llvm/include/c++/v1"
        - LD_LIBRARY_PATH="$HOME/llvm/lib":$LD_LIBRARY_PATH
      addons:
        apt:
          packages:
            - cmake
            - realpath
            - libboost-all-dev
            - linux-headers-generic

before_install:
  - wget http://downloads.sourceforge.net/ltp/lcov-1.13.tar.gz -O lcov.tar.gz
  - mkdir "$HOME/lcov"
  - tar xfz lcov.tar.gz -C "$HOME/lcov" --strip-components=1
  - export PATH=$HOME/lcov/bin:$PATH
  - wget http://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O llvm.tar.xz
  - mkdir "$HOME/llvm"
  - tar xf llvm.tar.xz -C "$HOME/llvm" --strip-components=1
  - export PATH=$HOME/llvm/bin:$PATH
  - pip install --user cpp-coveralls

script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir -p build/release
  - cd build/release
  - cmake -DCMAKE_BUILD_TYPE=Release ../..
  - make
  - make tests
  - ./tests

  - cd $TRAVIS_BUILD_DIR
  - mkdir -p build/debug
  - cd build/debug
  - cmake -DCMAKE_BUILD_TYPE=Debug ../..
  - ../../tools/coverage.sh

after_success:
  - cd $TRAVIS_BUILD_DIR
  - coveralls --root . -l build/debug/coverage.info -n
