#ifndef PIEX_HEADER_CONFIG
#define PIEX_HEADER_CONFIG

#define PIEX_OPTION_TRIVIAL 0

// socket

#define PIEX_OPTION_SOCKET_BUFFERED 1

#define PIEX_OPTION_SOCKET PIEX_OPTION_TRIVIAL
#define PIEX_OPTION_SOCKET_BUFFER_SIZE 4096

// order-book

#define PIEX_OPTION_ORDER_BOOK_RBTREE 1
#define PIEX_OPTION_ORDER_BOOK_HEAP 2

#define PIEX_OPTION_ORDER_BOOK PIEX_OPTION_TRIVIAL

#endif
