#ifndef PIEX_HEADER_CONFIG
#define PIEX_HEADER_CONFIG

#define PIEX_OPTION_TRIVIAL 0

// socket

#define PIEX_OPTION_SOCKET_BUFFERED 1

#define PIEX_OPTION_SOCKET PIEX_OPTION_TRIVIAL
#define PIEX_OPTION_SOCKET_BUFFER_SIZE 4096

#endif
