#ifndef PIEX_HEADER_CONFIG
#define PIEX_HEADER_CONFIG

#define PIEX_OPTION_TRIVIAL 0

// socket

#define PIEX_OPTION_SOCKET_BUFFERED 1
#define PIEX_OPTION_SOCKET_MULTITHREADED 2
#define PIEX_OPTION_SOCKET_MULTITHREADED_ATOMIC 3
#define PIEX_OPTION_SOCKET_MULTITHREADED_ATOMIC_FLUSH 4

#define PIEX_OPTION_SOCKET PIEX_OPTION_TRIVIAL
#define PIEX_OPTION_SOCKET_BUFFER_SIZE 4096
#define PIEX_OPTION_SOCKET_FLUSH_THRESHOLD 2048

// order-book

#define PIEX_OPTION_ORDER_BOOK_RBTREE 1
#define PIEX_OPTION_ORDER_BOOK_HEAP 2

#define PIEX_OPTION_ORDER_BOOK PIEX_OPTION_TRIVIAL

// benchmark

#define PIEX_OPTION_BENCHMARK_REQUEST_WINDOW_SIZE 1024

#endif
