#include "config/values.h"

#define PIEX_OPTION_SOCKET PIEX_OPTION_TRIVIAL
#define PIEX_OPTION_ORDER_BOOK PIEX_OPTION_ORDER_BOOK_HEAP
#define PIEX_OPTION_PACKETS PIEX_OPTION_TRIVIAL

#define PIEX_OPTION_BENCHMARK_REQUEST_WINDOW_SIZE 1024
