#include "config/values.h"

#define PIEX_OPTION_SOCKET PIEX_OPTION_SOCKET_MULTITHREADED_ATOMIC
#define PIEX_OPTION_SOCKET_BUFFER_SIZE 4096
#define PIEX_OPTION_ORDER_BOOK PIEX_OPTION_TRIVIAL

#define PIEX_OPTION_BENCHMARK_REQUEST_WINDOW_SIZE 1024
